export {
  getDB,
  saveVisitLocally,
  getLocalVisits,
  getPendingVisits,
  getErrorVisits,
  markVisitSynced,
  markVisitError,
  getVisit,
  deleteVisit,
  savePhotoLocally,
  getPhotosForVisit,
  getPhoto,
  deletePhoto,
  saveSnapshotLocally,
  saveSnapshotsLocally,
  getSnapshotsForVisit,
  getPendingSnapshots,
  markSnapshotSynced,
  clearAllData,
  estimateStorageUsage,
  checkQuotaBeforeSave,
  cleanupSyncedPhotos,
  StorageQuotaExceededError,
  type PromoCheckDB,
} from "./db"
