export {
  getDB,
  saveVisitLocally,
  getLocalVisits,
  getPendingVisits,
  getErrorVisits,
  markVisitSynced,
  markVisitError,
  getVisit,
  deleteVisit,
  getPhotosForVisit,
  getPhoto,
  deletePhoto,
  clearAllData,
  estimateStorageUsage,
  checkQuotaBeforeSave,
  cleanupSyncedPhotos,
  StorageQuotaExceededError,
  type PromoCheckDB,
} from "./db"
